#!/usr/bin/env python

"""
Launching script for the weekly weather table
Input arguments are passed to the main running script (wxtable.py)
"""

from util import get_config
import sys
from argparse import ArgumentParser
import wxtable

def parse_args():
    """
    Parse input arguments.
    A config file is required
    -ncdc forces downloading of new NCDC data
    """

    parser = ArgumentParser()
    parser.add_argument("config", help="Path to config file")
    parser.add_argument("-ncdc", "--download-ncdc", action="store_true", dest="d_ncdc",
                        help="Download new NCDC data (overwrites existing)")
    arguments = parser.parse_args()

    return arguments

args = parse_args()

# ==================================================================================================================== #
# Launch the main script
# ==================================================================================================================== #

wxtable.main(args)